apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: postgres_ds
    type: postgres
    url: postgres_db:5432
    database: test_db
    user: user
    secureJsonData:
      password: "pass"
    jsonData:
      sslmode: "disable"
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: true
